sudo: required
services:
  - docker

before_install:
  - docker build -t maheshd84/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run maheshd84/react-test npm test -- --coverage

after_success:
  - docker build -t maheshd84/multi-client ./client/
  - docker build -t maheshd84/multi-nginx ./nginx/
  - docker build -t maheshd84/multi-server ./server
  - docker build -t maheshd84/multi-worker ./worker

#Login to the DOCKER CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Take these images and puch them to docker hub

  - docker push maheshd84/multi-client
  - docker push maheshd84/multi-nginx
  - docker push maheshd84/multi-server
  - docker push maheshd84/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: Multi-docker-env
  bucket_name: "elasticbeanstalk-us-west-2-910572024355"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

